# Change these first
owner: stackexpress-shivam # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: StackExpress
    url: https://stackexpress-shivam.github.io/upptime/
  - name: APYL
    url: https://apyl.com
  - name: JodoHost
    url: https://www.jodohost.com
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://stackexpress.com/images/logo.34df6519.png
  name: StackExpress Uptime
  introTitle: "**Monitoring** for sites that matter."
  introMessage: Uptime Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
